### PR TITLE
Merge master (v0.20.6 release) to develop

### PR DESCRIPTION
**Pull request by ashchan**

### CODE REVIEW

**Review by xiaoluSF — APPROVED** [review]

**Comment by ashchan** [comment]
`uninstallFilter` test fails due to unknown (yet) reason.

**Comment by xiaoluSF** [comment]
Should I merge ignore CI ？

**Comment by ashchan** [comment]
> Should I merge ignore CI ？

NO. I'll merge when I figure this out.

**Comment by ashchan** [comment]
Merged this although test failed. Track the failing test with #50.

**Pull request merged**
