### PR TITLE
Rc/v0.24.0

### PR DESCRIPTION
**Pull request by xiaoluSF**
* [Optimization] Support new protocol version 2

### CODE REVIEW

**Review by ashchan — CHANGES_REQUESTED** [review]
Info.plist is still at `0.23.0`.

**Review by ashchan — APPROVED** [review]

**Comment by ashchan** [comment]
CI fails...

**Comment by xiaoluSF** [comment]
> CI fails...

Passed.

**Comment by ashchan** [comment]
> > CI fails...
> 
> Passed.

Any theory why this would happen?

**Comment by xiaoluSF** [comment]
> > > CI fails...
> > 
> > 
> > Passed.
> 
> Any theory why this would happen?

May be the cause of the network. RPCTest failed.

**Pull request merged**
